"""Content calendar generator for Chariot of the Self.

Given a series scaffold (e.g., "What the Gita knew about ___"), produce a
calendar of N episodes — each with a planned date, slug, working title,
topic, source text, and hook idea. The calendar is the input to a focused
6-week production run: each Monday the scriptwriter picks the next episode
from the list and starts drafting.

The calendar is generated by a chat call to MiniMax, with a system prompt
that encodes:
  - the brand-bible's series scaffolds (so titles stay on-pattern)
  - the hard-lines (no misattribution, no Sanskrit-only titles)
  - the 6-episode arc discipline from the showrunner cadence strategy

Optionally cross-references the latest competitor report so topics don't
duplicate what's already saturated in the niche.

CLI:
    python -m studio.calendar --series "What the Gita knew about ___" \\
        --episodes 6 --start 2026-07-06

    python -m studio.calendar --series "The mind, according to Patanjali" \\
        --episodes 6 --start 2026-07-06 \\
        --competitor-report competitor-reports/competitors-20260625T120000Z.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

from studio.config import load_settings
from studio.providers import minimax


# Canonical series scaffolds — copied from brand/brand-bible.md so the LLM
# can't invent its own. If you add a series in the brand-bible, add it here.
SERIES_SCAFFOLDS: dict[str, list[str]] = {
    "What the Gita knew about ___": ["work", "anger", "duty", "results",
                                     "fear", "action"],
    "The mind, according to Patanjali": ["attention", "distraction", "habit"],
    "Chanakya on ___": ["enemies", "money", "discipline", "friends"],
    "The Self and the witness": ["identity", "the observer", "ego"],
}


@dataclass
class CalendarEntry:
    episode_number: int
    planned_date: str
    slug: str
    working_title: str
    topic: str           # one line: what modern problem this video addresses
    source_text: str     # canonical text/figure the teaching comes from
    hook_idea: str       # one sentence: the 0:00-0:15 hook direction


@dataclass
class ContentCalendar:
    generated_at: str
    series: str
    start_date: str
    cadence_days: int
    episodes: list[CalendarEntry] = field(default_factory=list)


# ---- prompt ---------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are the calendar planner for "Chariot of the Self", a YouTube channel
that turns ancient Indian wisdom into practices for the modern mind.

Hard rules (never break):
1. NEVER invent a verse, sutra, or quote. If unsure of attribution, name the
   text only, no specific verse number.
2. Titles must lead with the modern problem. The source comes second.
3. One central idea per video, not five.
4. Each video must end with a concrete weekly practice.
5. Sanskrit terms must be translated into plain English in the working title.

Series scaffold (use the EXACT shape; do not invent a new one):
- "What the Gita knew about ___": work, anger, duty, results, fear, action
- "The mind, according to Patanjali": attention, distraction, habit
- "Chanakya on ___": enemies, money, discipline, friends
- "The Self and the witness": identity, the observer, ego

The 6-episode arc matters. Each title must:
- fit the series scaffold,
- cover a DIFFERENT modern problem from the other entries,
- be orderable (start with the most universally relatable problem;
  end with the most niche/esoteric).

Output format (strict JSON, no prose around it):
{"episodes": [
  {
    "working_title": "...",
    "topic": "one-line modern problem",
    "source_text": "e.g. 'Bhagavad Gita, Chapter 2 (Sankhya Yoga)'",
    "hook_idea": "one sentence describing the 0:00-0:15 hook"
  }
]}

Output exactly N episodes, no more, no less.\
"""


def _build_user_prompt(series: str, n: int, competitor_titles: list[str]) -> str:
    scaffold_list = SERIES_SCAFFOLDS.get(series)
    scaffold_hint = ""
    if scaffold_list:
        scaffold_hint = (
            f"\nSuggested slots for this series (use as a guide, adapt if better "
            f"modern problems exist): {scaffold_list}"
        )
    avoid_block = ""
    if competitor_titles:
        sample = "\n".join(f"- {t}" for t in competitor_titles[:15])
        avoid_block = (
            f"\nNiche context — top-view videos already winning on YouTube:\n"
            f"{sample}\n\n"
            f"Don't duplicate topics these already cover. Find angles they missed."
        )
    return (
        f"Series: {series}\n"
        f"Number of episodes: {n}{scaffold_hint}{avoid_block}\n\n"
        f"Plan {n} episodes for this series. Each must have a distinct modern "
        f"problem and a distinct source angle."
    )


# Same extraction pattern as studio.title_recommend — strict JSON preferred,
# fenced ```json``` blocks accepted, raw JSON fallback.
_JSON_FENCE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL)
_JSON_ANY = re.compile(r"(\{.*\})", re.DOTALL)


def _extract_json_object(text: str) -> dict:
    m = _JSON_FENCE.search(text)
    candidate = m.group(1) if m else None
    if not candidate:
        m = _JSON_ANY.search(text)
        candidate = m.group(1) if m else None
    if not candidate:
        raise ValueError(f"could not find JSON object in chat response: {text[:200]}")
    return json.loads(candidate)


# ---- slug + date helpers --------------------------------------------------

def _slugify(title: str, planned_date: date) -> str:
    """Channel convention: YYYY-MM-DD-kebab-topic (see CLAUDE.md)."""
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    slug = re.sub(r"-+", "-", slug)[:50] or "episode"
    return f"{planned_date.isoformat()}-{slug}"


def _schedule_dates(start: date, n: int, cadence_days: int) -> list[date]:
    """Return N dates at the requested cadence, starting from `start`.
    Cadence of 7 = weekly (default), 14 = bi-weekly, 1 = daily."""
    if cadence_days < 1:
        raise ValueError(f"cadence_days must be >= 1, got {cadence_days}")
    return [start + timedelta(days=cadence_days * i) for i in range(n)]


# ---- competitor cross-reference -------------------------------------------

def _load_competitor_titles(report_path: Path | None) -> list[str]:
    """If a competitor report exists, surface its top-video titles so the
    calendar LLM doesn't plan a duplicate."""
    if not report_path:
        # Auto-pick the most recent competitor-reports/*.json if present.
        auto = Path("competitor-reports")
        if auto.exists():
            reports = sorted(auto.glob("competitors-*.json"))
            if reports:
                report_path = reports[-1]
    if not report_path or not Path(report_path).exists():
        return []
    try:
        data = json.loads(Path(report_path).read_text())
    except json.JSONDecodeError:
        return []
    titles: list[str] = []
    for ch in data.get("channels", []):
        for v in ch.get("top_videos", []):
            t = v.get("title")
            if t:
                titles.append(t)
    return titles


# ---- core build ----------------------------------------------------------

def build_calendar(settings, *, series: str, n: int, start: date,
                   cadence_days: int = 7,
                   competitor_titles: list[str] | None = None) -> ContentCalendar:
    if series not in SERIES_SCAFFOLDS:
        # Allow custom series names — the LLM can attempt them — but warn.
        print(f"warning: '{series}' is not a canonical series scaffold. "
              f"Known: {list(SERIES_SCAFFOLDS)}. The LLM will still try, but "
              f"consider using a known scaffold for brand consistency.",
              file=sys.stderr)

    if competitor_titles is None:
        competitor_titles = []

    msgs = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user",
         "content": _build_user_prompt(series, n, competitor_titles)},
    ]
    url, headers, payload = minimax.chat_request(settings, msgs,
                                                  temperature=0.8, max_tokens=2000)
    text = minimax.post_chat(url, headers, payload)
    parsed = _extract_json_object(text)
    raw_episodes = parsed.get("episodes") or []

    dates = _schedule_dates(start, n, cadence_days)
    entries = []
    for i, raw in enumerate(raw_episodes[:n]):
        title = raw.get("working_title", "").strip() or f"Episode {i+1}"
        entries.append(CalendarEntry(
            episode_number=i + 1,
            planned_date=dates[i].isoformat(),
            slug=_slugify(title, dates[i]),
            working_title=title,
            topic=raw.get("topic", "").strip(),
            source_text=raw.get("source_text", "").strip(),
            hook_idea=raw.get("hook_idea", "").strip(),
        ))
    return ContentCalendar(
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        series=series,
        start_date=start.isoformat(),
        cadence_days=cadence_days,
        episodes=entries,
    )


def write_calendar(calendar: ContentCalendar, out_dir: Path) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9]+", "-", calendar.series.lower()).strip("-")[:40] or "calendar"
    out_path = out_dir / f"calendar-{slug}-{calendar.start_date}.json"
    out_path.write_text(json.dumps(asdict(calendar), indent=2))
    return out_path


# ---- CLI ------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="studio.calendar",
        description="Generate a content calendar of N episodes for a series.")
    parser.add_argument("--series", required=True,
        help=f"Series scaffold. Known: {list(SERIES_SCAFFOLDS)}")
    parser.add_argument("--episodes", "-n", type=int, default=6,
        help="Number of episodes (default: 6 — the showrunner's mini-catalogue)")
    parser.add_argument("--start", required=True,
        help="Start date (YYYY-MM-DD, e.g. the next Monday)")
    parser.add_argument("--cadence-days", type=int, default=7,
        help="Days between episodes (default: 7 = weekly)")
    parser.add_argument("--competitor-report",
        help="Optional path to competitor-reports/*.json to avoid duplicates")
    parser.add_argument("--out", default="content-calendars/",
        help="Output directory (default: content-calendars/)")
    args = parser.parse_args(argv)

    settings = load_settings()
    try:
        start = date.fromisoformat(args.start)
    except ValueError:
        print(f"error: --start must be YYYY-MM-DD, got {args.start!r}",
              file=sys.stderr)
        return 2

    competitor_titles = _load_competitor_titles(
        Path(args.competitor_report) if args.competitor_report else None)

    cal = build_calendar(settings, series=args.series, n=args.episodes,
                         start=start, cadence_days=args.cadence_days,
                         competitor_titles=competitor_titles)
    out = write_calendar(cal, Path(args.out))
    print(f"wrote {out} ({len(cal.episodes)} episodes)")
    for e in cal.episodes:
        print(f"  {e.episode_number}. [{e.planned_date}] {e.working_title}")
    return 0


if __name__ == "__main__":
    sys.exit(main())